name: build
on:
  push: [ ]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.8'
      - name: build
        run: ./scripts/build.sh
      - name: example
        run: ./scripts/build-example.sh

